fixing variables for metricfile

diff --git a/bin/sisrs b/bin/sisrs
--- a/bin/sisrs
+++ b/bin/sisrs
@@ -37,22 +37,21 @@ Default settings can be changed using the following flags:
     -a : use to specify the folder containing the folders of reads
     -n : use to specify the number of reads required to call a base at a site
     -t : use to specify the threshold for calling a site; e.g. 0.99 means that >99% of bases for that taxon must be one allele; only recommended for low ploidy with <3 individuals
-    -s : use to specify the steps to skip: 1 skips finding contigs, 2 also skips aligning reads to contigs; 3 skips to just identifying whether sites are variable among taxa
+    -s : use to specify the steps to skip: 1 skips making the composite genome; 2 also skips aligning reads to the composite reference; 3 also skips getting data for each site and mapping the composite genome to a known reference if available; 4 skips to identifying whether sites are variable among taxa given data for each site for each taxon
 
-    Example command: ./sisrs -r ./reference.fasta -p 40 -f fastq -m 4 -a ./fastq_data/"
+    Example command: ./sisrs -g 50000000 -r ./reference.fasta -p 40 -f fastq -m 4 -a test_data"
     }
-date > time_and_command_log.txt
+
 #use defaults or input values
 KMER=21
 MINREAD=3
 PROCESSORS=1
-FORMAT=fastq
 MAINFOLDER=.
 THRESHOLD=1
 SKIP=0
 REPEAT=0
 
-while getopts q:g:r:k:p:f:m:a:n:s:t:h option
+while getopts q:g:r:k:p:m:a:n:s:t:h option
 do
 case "${option}"
     in
@@ -61,7 +60,6 @@ case "${option}"
         r) REFFILE=${OPTARG};;
         k) KMER=${OPTARG};;
         p) PROCESSORS=${OPTARG};;
-        f) FORMAT=${OPTARG};;
         m) MISSING=${OPTARG};;
         a) MAINFOLDER=${OPTARG};;
         n) MINREAD=${OPTARG};;
@@ -72,7 +70,22 @@ case "${option}"
         esac
 done
 
-echo $KMER $MINREAD $THRESHOLD $SKIP $PROCESSORS >> time_and_command_log.txt
+echo "" > metrics_file.txt
+echo "Name of assembler:
+Name of data set:
+Total size of data set:" > metrics_file.txt
+echo "Enter the name of your assembler"
+read NAMEOFASSEMBLER
+echo "You are using $NAMEOFASSEMBLER as your assembler"
+#Need to find way to append line 81 to line 1 of metrics_file.txt
+echo "$NAMEOFASSEMBLER" >> metrics_file.txt
+#Need to find way to append line 83 to line 2 of metrics_file.txt
+pwd >> metrics_file.txt
+
+var=`date`
+STARTTIME=`date`
+echo "$STARTTIME"
+echo "$STARTTIME" >> metrics_file.txt
 
 if [ -z $1 ]; then
     echo "You are using the default values. If this is incorrect, rerun SISRS using the correct flags. For more information run sisrs -h"
@@ -81,203 +94,138 @@ fi
 DIRS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"    #where is the sisrs file?
 DIR=$( dirname ${DIRS} )                                    #go one level up from location of sisrs file
 MAINFOLDER=$( echo "${MAINFOLDER}" | sed -e "s/\/*$//" )    #remove trailing / if necessary
-command -v velveth >/dev/null 2>&1 || { echo >&2 "Velvet must be installed to run SISRS. The installation folder must be in your $PATH. Aborting."; exit 1; }
-command -v bowtie2 >/dev/null 2>&1 || { echo >&2 "Bowtie2 must be installed to run SISRS. The installation folder must be in your $PATH. Aborting."; exit 1; }
 
-#check for availability of parallel
-command -v parallel >/dev/null 2>&1 || { echo >&2 "SISRS will run faster if you install parallel."; }
-POUT=$(parallel echo ::: A)
+which velveth &>/dev/null
+[ $? -eq 0 ] || { echo "Velvet must be installed to run SISRS. The installation folder must be in your path. Aborting."; exit 1; }
+which bowtie2 &>/dev/null
+[ $? -eq 0 ] || { echo "Bowtie2 must be installed to run SISRS. The installation folder must be in your path. Aborting."; exit 1; }
+which parallel &>/dev/null
+[ $? -eq 0 ] || { echo "GNU parallel must be installed to run SISRS. The installation folder must be in your path. Aborting."; exit 1; }
 
-FILELIST=( $( find "${MAINFOLDER}" -name "*R1*${FORMAT}" ) )     #all FORMAT file paths as array
-declare -a ALLFOLDERLIST=()
-for F in "${FILELIST[@]}"; do ALLFOLDERLIST+=("$( dirname "${F}" )"); done       #array of directories containing FORMAT files
-FOLDERLIST=( $(echo "${ALLFOLDERLIST[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ') )  #sorted unique list of folders with paired FORMAT files as array
+#get paired fastq
+FILELIST=( $( find "${MAINFOLDER}" -name "*R1*fastq" ) )     #all fastq file paths as array
+if [[ ${#FILELIST[@]} -gt 0 ]]; then
+    declare -a ALLFOLDERLIST=()
+    for F in "${FILELIST[@]}"; do ALLFOLDERLIST+=("$( dirname "${F}" )"); done       #array of directories containing fastq files
+    FOLDERLIST=( $(echo "${ALLFOLDERLIST[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ') )  #sorted unique list of folders with paired fastq files as array
+fi
 
-#FILELISTQ=$( find ${MAINFOLDER} -name *reads*fastq )
-#FILELISTA=$( find ${MAINFOLDER} -name *reads*fasta )
-#FILELISTG=$( find ${MAINFOLDER} -name *Genomic*fasta )
-#FOLDERLIST=$( dirname ${FILELIST} | sort -u | uniq )
-#FOLDERLISTA=$( dirname ${FILELISTA} | sort -u | uniq )
-#FOLDERLISTQ=$( dirname ${FILELISTQ} | sort -u | uniq )
-#FILELISTB=( ${FILELIST[@]} ${FILELISTA[@]} )    #extra for extra files
-#FOLDERLISTB=( ${FOLDERLIST[@]} ${FOLDERLISTA[@]} )    #extra for extra files
+#get unpaired fastq
+FILELISTA=( $( find "${MAINFOLDER}" -name "*fastq" ) )     
+FILELISTU=()
+for F in "${FILELISTA[@]}"; do
+    if [[ $F != *R1* ]] && [[ $F != *R2* ]] && [[ $F != *shuffled* ]] && [[ $F != *sampled* ]]; then FILELISTU+=${F}
+    fi
+done
+if [[ ${#FILELISTU[@]} -gt 0 ]]; then
+    declare -a ALLFOLDERLISTU=()
+    for F in "${FILELISTU[@]}"; do ALLFOLDERLISTU+=("$( dirname "${F}" )"); done       #array of directories containing fastq files
+    FOLDERLISTU=( $(echo "${ALLFOLDERLISTU[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ') )  #sorted unique list of folders with unpaired fastq files as array
+fi
+FOLDERLISTA=( $(echo "${FOLDERLISTU[@]} ${FOLDERLIST[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ') )
 
-if [ -z "$MISSING" ]; then MISSING=$((${#FOLDERLIST[@]} - 2)); fi    #allowed to have all missing except 2 unless otherwise specified
+if [ -z "$MISSING" ]; then MISSING=$((${#FOLDERLISTA[@]} - 2)); fi    #minimum of data for 2 species unless otherwise specified
+
+echo ${Name_of_Assembler} >> ${MAINFOLDER}/metrics_file.txt
+echo ${Name_of_Data_set} >> ${MAINFOLDER}/metrics_file.txt
+echo ${Total_Data_Set_Size} >> ${MAINFOLDER}/metrics_file.txt
+echo ${GENOMESIZE} >> ${MAINFOLDER}/metrics_file.txt
+echo ${Contig_len} >> ${MAINFOLDER}/metrics_file.txt
+echo ${Contig_num} >> ${MAINFOLDER}/metrics_file.txt
 
 #use skip flag to skip various parts of the script
-date >> time_and_command_log.txt
 if [ "$SKIP" -lt 1 ]; then
-    #use parallel if available
-
     if [ -n "${GENOMESIZE}" ]; then
         NUMER=$((10*${GENOMESIZE}))
-        DENOM=$((100*2*${#FOLDERLIST[@]}))      #assumes 100bp reads - add option in future
+        DENOM=$((100*2*${#FOLDERLISTA[@]}))      #assumes 100bp reads - add option in future
         LEFTREADS=$((${NUMER}/${DENOM}))
-        
-        #subsample data and shuffle
-        if [ "${POUT}" = 'A' ]; then
-            parallel --jobs "${PROCESSORS}" "python ${DIR}/libexec/sisrs/sub_sample_for_velvet_unshuff.py ${LEFTREADS} {}" ::: "${FOLDERLIST[@]}"
-        else
-        NPROC=0
-        for FOLDER in "${FOLDERLIST[@]}"; do
-            ( python ${DIR}/libexec/sisrs/sub_sample_for_velvet_unshuff.py ${LEFTREADS} ${FOLDER} ) &
-            NPROC=$(($NPROC+1))
-            if [ "$NPROC" -ge "${PROCESSORS}" ]; then wait
-                NPROC=0
-            fi
-        done
-        wait
-        fi
-
-    else    
-        #shuffle paired end reads together if not subsampling 
-        if [ "${POUT}" = 'A' ]; then
-            parallel --jobs "${PROCESSORS}" "perl ${DIR}/libexec/sisrs/shuffleSequences_fastq.pl" '{} $(echo {} | sed 's/R1/R2/') $(echo {} | sed 's/R1/shuffled/')' ::: "${FILELIST[@]}"
-        else
-        NPROC=0
-        for FILE in "${FILELIST[@]}"; do
-            ( perl ${DIR}/libexec/sisrs/shuffleSequences_${FORMAT}.pl ${FILE} $(echo ${FILE}|sed 's/R1/R2/') $(echo ${FILE}|sed 's/R1/shuffled/') ) &
-            NPROC=$(($NPROC+1))
-            if [ "$NPROC" -ge "${PROCESSORS}" ]; then wait
-                NPROC=0
-            fi
-        done
-        wait
-        fi
+        parallel --jobs "${PROCESSORS}" "python ${DIR}/libexec/sisrs/sub_sample_for_velvet_unshuff.py ${LEFTREADS} {}" ::: "${FOLDERLISTA[@]}"   #subsample data and shuffle 
+    else        #shuffle paired end reads together if not subsampling         
+        parallel --jobs "${PROCESSORS}" "perl ${DIR}/libexec/sisrs/shuffleSequences_fastq.pl" '{} $(echo {} | sed 's/R1/R2/') $(echo {} | sed 's/R1/shuffled/')' ::: "${FILELIST[@]}"
+        for F in "${FILELISTU[@]}"; do ln $F $(dirname "${F}")/subsampled_$(basename "${F}"); done
     fi
     
-    date >> time_and_command_log.txt
     #make reference contigs - velveth
     if [ -n "${REFFILE}" ]; then
-        velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary -fasta -reference ${REFFILE} -${FORMAT} -shortPaired ${MAINFOLDER}/*/*shuffled*${FORMAT}
+        if [[ ${#FILELISTU[@]} -gt 0 ]]; then
+            if [[ ${#FILELIST[@]} -gt 0 ]]; then
+                velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary -fasta -reference ${REFFILE} -fastq -shortPaired ${MAINFOLDER}/*/*shuffled*fastq -short ${MAINFOLDER}/*/subsampled*fastq
+            else
+                velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary -fasta -reference ${REFFILE} -fastq -short ${MAINFOLDER}/*/subsampled*fastq
+            fi
+        else
+            velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary -fasta -reference ${REFFILE} -fastq -shortPaired ${MAINFOLDER}/*/*shuffled*fastq
+        fi
     else
-        velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary -${FORMAT} -shortPaired ${MAINFOLDER}/*/*shuffled*${FORMAT}
+        if [[ ${#FILELISTU[@]} -gt 0 ]]; then
+            if [[ ${#FILELIST[@]} -gt 0 ]]; then
+                velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary -fastq -shortPaired ${MAINFOLDER}/*/*shuffled*fastq -short ${MAINFOLDER}/*/subsampled*fastq
+            else
+                velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary ${REFFILE} -fastq -short ${MAINFOLDER}/*/subsampled*fastq
+            fi
+        else
+            velveth ${MAINFOLDER}/velvetoutput ${KMER} -create_binary ${REFFILE} -fastq -shortPaired ${MAINFOLDER}/*/*shuffled*fastq
+        fi
     fi
     echo ==== Velveth is finished ====
     
-    date >> time_and_command_log.txt
     velvetg ${MAINFOLDER}/velvetoutput -exp_cov auto -cov_cutoff auto# -min_contig_lgth 100     #run velvet - output contigs
     echo ==== Velvetg is finished ====
     
-    date >> time_and_command_log.txt
-    bowtie2-build ${MAINFOLDER}/velvetoutput/contigs.fa ${MAINFOLDER}/velvetoutput/contigs      #index contigs
 fi  #skipped making contigs if SKIP>0
 
 if [ "$SKIP" -lt 2 ]; then
+    bowtie2-build ${MAINFOLDER}/velvetoutput/contigs.fa ${MAINFOLDER}/velvetoutput/contigs      #index contigs
+    
     #align reads to contigs
-    date >> time_and_command_log.txt
     for FILE in "${FILELIST[@]}"; do
         NAME=$( echo ${FILE} | sed 's/R1//' | sed 's/\.[^.]*$//' ) #includes folder but not the read or the extension
         echo ==== Aligning ${NAME} ====
         #N=1 allows a mismatch #x The basename of the index for the reference genome
-        if [ "${FORMAT}" == "fastq" ]; then
-            ( bowtie2 -p "${PROCESSORS}" -N 1 --local -x ${MAINFOLDER}/velvetoutput/contigs -1 ${FILE} -2 $( echo ${FILE}|sed 's/R1/R2/' ) > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) | samtools view -Su -F 4 - | samtools sort - ${NAME} ) 
-        else
-            ( bowtie2 -p "${PROCESSORS}" -N 1 -f --local -x ${MAINFOLDER}/velvetoutput/contigs -1 ${FILE} -2 $( echo ${FILE}|sed 's/R1/R2/' ) > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) |  samtools view -Su -F 4 - | samtools sort - ${NAME} ) 
-        fi
+        bowtie2 -p "${PROCESSORS}" -N 1 --local -x ${MAINFOLDER}/velvetoutput/contigs -1 ${FILE} -2 $( echo ${FILE}|sed 's/R1/R2/' ) > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) | samtools view -Su -F 4 - | samtools sort - ${NAME}
+    done
+    for FILE in "${FILELISTU[@]}"; do
+        NAME=$( echo ${FILE} | sed 's/\.[^.]*$//' ) #includes folder but not the read or the extension
+        echo ==== Aligning ${NAME} ====
+        #N=1 allows a mismatch #x The basename of the index for the reference genome
+        bowtie2 -p "${PROCESSORS}" -N 1 --local -x ${MAINFOLDER}/velvetoutput/contigs -U ${FILE} > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) | samtools view -Su -F 4 - | samtools sort - ${NAME}
     done
     echo ==== Done Aligning ====
-    
-    if [ -n "${REPEAT}" = 1 ]; then
-        #remake contigs for each taxon - do not allow indels
-        parallel -j "${PROCESSORS}" "samtools merge {}/merged.bam {}/*.bam" ::: "${FOLDERLIST[@]}"       #merge bam files
-        for FOLDER in "${FOLDERLIST[@]}"; do
-            if [ ! -f ${FOLDER}/merged.bam ]; then                   #samtools won't merge one file - need to copy
-                A=${FOLDER}/*bam
-                ln $(echo "$A") ${FOLDER}/merged.bam
-            fi
-        done
-        parallel -j "${PROCESSORS}" "samtools mpileup -f ${MAINFOLDER}/velvetoutput/contigs.fa" '{}/merged.bam -A > {}/merged.pileups' ::: "${FOLDERLIST[@]}"
-        parallel -j "${PROCESSORS}" "python ${DIR}/libexec/sisrs/make_species_contigs.py ${MAINFOLDER}/velvetoutput/contigs.fa {}/merged.pileups" ::: "${FOLDERLIST[@]}"
-        
-        #index all new contigs
-        parallel -j "${PROCESSORS}" "bowtie2-build {}/contigs.fa {}/contigs"  ::: "${FOLDERLIST[@]}"
-        
-        #realign to taxon-specific data
-        for FILE in "${FILELIST[@]}"; do
-            NAME=$( echo ${FILE} | sed 's/R1//' | sed 's/\.[^.]*$//' ) #includes folder but not the read or the extension
-            echo ==== Aligning ${NAME} ====
-            bowtie2 -p "${PROCESSORS}" -N 1 --local -x $(dirname ${FILE})/contigs -1 ${FILE} -2 $( echo ${FILE}|sed 's/R1/R2/' ) > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) | samtools view -Su -F 4 - | samtools sort - ${NAME}
-        done
-        parallel -j "${PROCESSORS}" "rm {}/merged.pileups" ::: "${FOLDERLIST[@]}"
-        parallel -j "${PROCESSORS}" "rm {}/merged.bam" ::: "${FOLDERLIST[@]}"
-    
-        echo ==== Done Repeated Aligning ====
-    fi    
 fi #also skipped aligning reads if SKIP>1
     
-
 if [ "$SKIP" -lt 3 ]; then
     #index bam
-    date >> time_and_command_log.txt
-    if [ "${POUT}" = 'A' ]; then
-            parallel --jobs "${PROCESSORS}" 'samtools index $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).bam' ::: "${FILELIST[@]}"
-    else
-        NPROC=0
-        for FILE in "${FILELIST[@]}"; do
-            NAME=$( echo ${FILE} | sed 's/R1//' | sed 's/\.[^.]*$//' )
-            ( samtools index ${NAME}.bam ) &
-            NPROC=$(($NPROC+1))
-            if [ "$NPROC" -ge "${PROCESSORS}" ]; then wait
-                NPROC=0
-            fi
-        done
-        wait
-    fi
+    parallel --jobs "${PROCESSORS}" 'samtools index $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).bam' ::: "${FILELIST[@]}" "${FILELISTU[@]}"
     echo ==== Done Indexing Bam Files ====
     
     #get pileups for data
-    date >> time_and_command_log.txt
-    if [ "${POUT}" = 'A' ]; then
-        parallel --jobs "${PROCESSORS}" "samtools mpileup -f ${MAINFOLDER}/velvetoutput/contigs.fa" '$( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).bam -A > $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).pileups' ::: "${FILELIST[@]}"
-    else
-        NPROC=0
-        for FILE in "${FILELIST[@]}"; do
-            NAME=$( echo ${FILE} | sed 's/R1//' | sed 's/\.[^.]*$//' )
-            ( samtools mpileup -f ${MAINFOLDER}/velvetoutput/contigs.fa ${NAME}.bam -A > ${NAME}.pileups ) &
-            NPROC=$(($NPROC+1))
-            if [ "$NPROC" -ge "${PROCESSORS}" ]; then
-                wait
-                NPROC=0
-            fi
-        done
-        wait
-    fi
+    parallel --jobs "${PROCESSORS}" "samtools mpileup -f ${MAINFOLDER}/velvetoutput/contigs.fa" '$( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).bam -A > $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).pileups' ::: "${FILELIST[@]}" "${FILELISTU[@]}"
     echo ==== Done Piling Up ====
        
     #map contigs to reference
-    date >> time_and_command_log.txt
     if [ -n "${REFFILE}" ]; then
         NAME=$( echo ${REFFILE} | sed 's/\.[^.]*$//' )
         bowtie2-build ${REFFILE} ${NAME}        #bowtie2-build [options]* <reference_in> <bt2_base>
-        ( bowtie2 -p ${PROCESSORS} -N 1 -x ${NAME} -f -U ${MAINFOLDER}/velvetoutput/contigs.fa > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) -S ${MAINFOLDER}/velvetoutput/align_contigs.sam )    #bowtie2 -x <ref_base> -U <fq files> -S <output sam>
+        bowtie2 -p ${PROCESSORS} -N 1 -x ${NAME} -f -U ${MAINFOLDER}/velvetoutput/contigs.fa > >(tee ${NAME}_stdout.log) 2> >(tee ${NAME}_stderr.log >&2) -S ${MAINFOLDER}/velvetoutput/align_contigs.sam    #bowtie2 -x <ref_base> -U <fq files> -S <output sam>
     echo ==== Done Mapping Contigs ====
     fi
 fi  #also skipped bam, pileups, reference mapping if SKIP>2
 
 if [ "$SKIP" -lt 4 ]; then
     #put base for each site in a dictionary (allows no variation when calling sites)
-    date >> time_and_command_log.txt
-    if [ "${POUT}" = 'A' ]; then
-        parallel --jobs "${PROCESSORS}" "${DIR}/libexec/sisrs/get_pruned_dict.py {} ${MINREAD} ${THRESHOLD}" ::: "${FOLDERLIST[@]}"
-    else
-        NPROC=0
-        for FOLDER in "${FOLDERLIST[@]}"; do
-            ( ${DIR}/libexec/sisrs/get_pruned_dict.py ${FOLDER} ${MINREAD} ${THRESHOLD} ) &
-            NPROC=$(($NPROC+1))
-            if [ "$NPROC" -ge "${PROCESSORS}" ]; then wait
-                NPROC=0
-            fi
-        done
-        wait
-    fi
+    parallel --jobs "${PROCESSORS}" "${DIR}/libexec/sisrs/get_pruned_dict.py {} ${MINREAD} ${THRESHOLD}" ::: "${FOLDERLISTA[@]}"
     echo ==== Done Identifying Fixed Sites Without Error ====
 fi  #end of skip
 
-date >> time_and_command_log.txt
 if [ -n "${REFFILE}" ]; then
     ( ${DIR}/libexec/sisrs/get_alignment.py ${MISSING} ${REFFILE} ${MAINFOLDER} )
 else
     ( ${DIR}/libexec/sisrs/get_alignment.py ${MISSING} X ${MAINFOLDER} )
 fi
+
+var=`date`
+ENDTIME=`date`
+echo "$ENDTIME"
+echo "$ENDTIME" >> metrics_file.txt
+
 echo ==== DONE ====
